# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京小超

on:
  workflow_dispatch:
  schedule:
    - cron: '18 1-23/3 * * *'
  watch:
    types: started
  repository_dispatch:
    types: superMarket
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - uses: actions/checkout@v2
        with:
          ref: "jd"
          persist-credentials: false
      - name: run scripts
        run: |
          cp -f update_env.sh ~/update_env.sh && chmod 755 ~/update_env.sh && ~/update_env.sh
      - name: '运行 【东东超市】'
        run: |
          bash ./run_scripts.sh jd_superMarket.js
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          DD_BOT_TOKEN_SPEC: ${{ secrets.DD_BOT_TOKEN_SPEC }}
          DD_BOT_SECRET_SPEC: ${{ secrets.DD_BOT_SECRET_SPEC }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          jdSuperMarketUpgrade: ${{ secrets.SUPERMARKET_UPGRADE }}
          jdBusinessCircleJump: ${{ secrets.BUSINESS_CIRCLE_JUMP }}
          SUPERMARKET_SHARECODES: ${{ secrets.SUPERMARKET_SHARECODES }}
          SUPERMARKET_LOTTERY: "true"
      - name: '运行 【京东健康任务】'
        run: |
          bash ./concurrency.sh jd_health_collect.js
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          DD_BOT_TOKEN_SPEC: ${{ secrets.DD_BOT_TOKEN_SPEC }}
          DD_BOT_SECRET_SPEC: ${{ secrets.DD_BOT_SECRET_SPEC }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          jdSuperMarketUpgrade: ${{ secrets.SUPERMARKET_UPGRADE }}
          jdBusinessCircleJump: ${{ secrets.BUSINESS_CIRCLE_JUMP }}
          SUPERMARKET_SHARECODES: ${{ secrets.SUPERMARKET_SHARECODES }}
          SUPERMARKET_LOTTERY: "true"
